Llano.Web/ViewComponents/HeaderViewComponent.cs
using Llano.Interfaces;
using Llano.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Llano.Web.ViewComponents
{
    public class HeaderViewComponent: ViewComponent
    {
        #region ---------------- Dependencias  ---------------

        private readonly IResourceService _resourceService;

        public HeaderViewComponent
            (
            IResourceService resourceService
            )
        {
            this._resourceService = resourceService;
        }

        #endregion


        public async Task<IViewComponentResult> InvokeAsync(HeaderViewModel model)
        {
            var notifications =  await this._resourceService.ResourcesWithoutRead();

            var newModel = new HeaderViewModel()
            {
                Notifications = notifications
            };

            return View(newModel);
        }

    }
}

Llano.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en" class="no-js">
<head>
    <title>@ViewData["Title"] - Llano.Web</title>

    <!-- Meta -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="keywords" content="llano">
    <meta name="description" content="LLanoApp es una iniciativa que busca salvaguardar el lexìco llanero">
    <meta name="author" content="Breidy Alexis Acevedo">

    <!-- Favicon -->
    <link rel="shortcut icon" href="~/favicon.ico" type="image/x-icon">

    <!-- Web Fonts -->
    <link href="//fonts.googleapis.com/css?family=Open+Sans:300,400,600,700" rel="stylesheet">

    <!-- Components Vendor Styles -->
    <link rel="stylesheet" href="~/vendor/font-awesome/css/all.min.css">
    <link rel="stylesheet" href="~/vendor/malihu-custom-scrollbar-plugin/jquery.mCustomScrollbar.css">

    <!-- Theme Styles -->
    <link rel="stylesheet" href="~/css/theme.css">
    <!-- Custom Styles-->
    <link rel="stylesheet" href="~/css/site.css">


    <!-- Player Audio Styles -->
    <link rel="stylesheet" href="~/lib/jPlayer-2.9.2/dist/skin/blue.monday/css/jplayer.blue.monday.css">



    <!-- Custom Charts -->
    <style>
        .js-doughnut-chart {
            width: 70px !important;
            height: 70px !important;
        }
    </style>



</head>


<body>

    @await Component.InvokeAsync("Header")

    @RenderBody()

    @RenderSection("scripts", required: false)


    <!-- Global Vendor -->
    <script src="~/vendor/jquery/dist/jquery.min.js"></script>
    <script src="~/vendor/jquery-migrate/jquery-migrate.min.js"></script>
    <script src="~/vendor/popper.js/dist/umd/popper.min.js"></script>
    <script src="~/vendor/bootstrap/bootstrap.min.js"></script>

    <!-- Plugins -->
    <script src="~/vendor/malihu-custom-scrollbar-plugin/jquery.mCustomScrollbar.concat.min.js"></script>
    <script src="~/vendor/chart.js/dist/Chart.min.js"></script>

    <!-- Initialization  -->
    <script src="~/js/sidebar-nav.js"></script>
    <script src="~/js/main.js"></script>
    <script src="~/js/dashboard-page-scripts.js"></script>

    <!-- Player Audio -->
    <script type="text/javascript" src="~/lib/jPlayer-2.9.2/src/javascript/jplayer/jquery.jplayer.js"></script>

    <script type="text/javascript">
        $(document).ready(function () {

            $("#jquery_jplayer_1").jPlayer({
                ready: function () {

                    var audio = $("#urlAudio").val(); 
                    var urAudio = "https://www.llanoapp.studio" + audio;
                    $(this).jPlayer("setMedia", {
                        m4a: urAudio,
                        oga: urAudio
                    });
                },
                cssSelectorAncestor: "#jp_container_1",
                swfPath: "/js",
                supplied: "m4a, oga",
                useStateClassSkin: true,
                autoBlur: false,
                smoothPlayBar: true,
                keyEnabled: true,
                remainingDuration: true,
                toggleDuration: true
            });


            // Formulario Discarded
            var submit = "";
            $("#submitDescartar").click(function (e) {
                submit = "submitDescartar";
                var $myForm = $('#myForm');

                if (!$myForm[0].checkValidity()) {
                    // If the form is invalid, submit it. The form won't actually submit;
                    // this will just cause the browser to display the native HTML5 error messages.
                    $myForm.find(':submit').click();
                } else {
                    e.preventDefault();

                    $("#resourceDisableHide").val(true);


                    $('#modalDiscarded').modal('show');
                    return false;

                }
            });

            // Formulario Approved
            $("#submitApproved").click(function (e) {
                submit = "submitApproved";
                var $myForm = $('#myForm');

                if (!$myForm[0].checkValidity()) {
                    // If the form is invalid, submit it. The form won't actually submit;
                    // this will just cause the browser to display the native HTML5 error messages.
                    $myForm.find(':submit').click();
                } else {
                    e.preventDefault();

                    $("#resourceDisableHide").val(false);


                    $('#modalApproved').modal('show');
                    return false;

                }
            });

            $(document).on('submit', '.validateDontSubmit', function (e) {

                if (submit == "submitDescartar") {
                    var $myForm = $('#formDiscarded');
                } else {
                    var $myForm = $('#formApproved');
                }


                if (!$myForm[0].checkValidity()) {
                    // If the form is invalid, submit it. The form won't actually submit;
                    // this will just cause the browser to display the native HTML5 error messages.
                    e.preventDefault();
                    $myForm.find(':submit').click();
                    return false;
                }
            })

            $("#myForm").submit(function () {
                if (submit == "submitDescartar") {
                    $("#messageHide").val($("#messageDiscardedShow").val());
                } else {
                    $("#messageHide").val($("#messageApprovedShow").val());

                }

            });

            //formular
            $("#eliminarUsuario").click(function (e) {
                var $myForm = $('#formUser');

                if (!$myForm[0].checkValidity()) {
                    // If the form is invalid, submit it. The form won't actually submit;
                    // this will just cause the browser to display the native HTML5 error messages.
                    $myForm.find(':submit').click();
                } else {
                    e.preventDefault();

                    $('#modalEliminarUsuario').modal('show');
                    return false;

                }
            });



        });
    </script>

</body>

</html>