Llano.Web/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Llano.Interfaces;
using Llano.Models;
using Llano.ViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Llano.Web.Controllers
{
    public class UserController : Controller
    {

        #region ---------------- Injecccion de dependencias -----------------

        private readonly UserManager<Customer> _userManager;
        private readonly IResourceService _resourceServices;
        private readonly IResourceService _resourceService;
        private readonly IFcmService _fcmService;

        public UserController(
            UserManager<Customer> userManager,
            IResourceService resourceServices,
              IResourceService resourceService,
              IFcmService fcmService
            )
        {
            _userManager = userManager;
            _resourceServices = resourceServices;
            this._resourceService = resourceService;
            this._fcmService = fcmService;
        }

        #endregion

        public async Task<IActionResult> Index()
        {
            var users = await this._userManager.Users.ToListAsync();

            //esto evita que se muestre el usuario administrador
            var usersWithOutAdmin = users.Where(x => x.PhoneNumber != null).ToList();

            return View(usersWithOutAdmin);
        }

        public async Task<IActionResult> Read(string UserId)
        {
            var user = await this._userManager.FindByIdAsync(UserId);
            var resources = await this._resourceServices.GetForUserId(UserId);

            CustomerMessageViewModels CustomerMessageViewModels = new CustomerMessageViewModels
            {
                UserApplication = user,
                Resources = resources.ToList()
            };

            return View(CustomerMessageViewModels);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(CustomerMessageViewModels CustomerMessageViewModels)
        {
            try
            {
                var message = CustomerMessageViewModels.Message;
                var user = await this._userManager.FindByIdAsync(CustomerMessageViewModels.UserApplication.Id);
               

                await this._userManager.UpdateAsync(user);

                //busco si tiene recursos 

                var resourcesForThisUser =  await this._resourceService.GetForUserId(user.Id);

                foreach (var resource in resourcesForThisUser)
                {
                    await this._resourceService.Delete(resource.Id);
                }

                var userDelete = await this._userManager.DeleteAsync(user);

                var notification = new Notification
                {
                    Title = "Usuario Eliminado",
                    Body = message,
                    CustomerId = user.Id,
                    Type = "NotificationUser"

                };

                await this._fcmService.SendNotification(notification);





                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {

                throw ex;
            }

        }

    }
}

Llano.Web/ViewComponents/SidebarViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Llano.Web.ViewComponents
{
    public class SidebarViewComponent: ViewComponent
    {
#pragma warning disable CS1998 // El método asincrónico carece de operadores "await" y se ejecutará de forma sincrónica. Puede usar el operador 'await' para esperar llamadas API que no sean de bloqueo o 'await Task.Run(...)' para hacer tareas enlazadas a la CPU en un subproceso en segundo plano.
        public async Task<IViewComponentResult> InvokeAsync(SidebarViewComponent model)
#pragma warning restore CS1998 // El método asincrónico carece de operadores "await" y se ejecutará de forma sincrónica. Puede usar el operador 'await' para esperar llamadas API que no sean de bloqueo o 'await Task.Run(...)' para hacer tareas enlazadas a la CPU en un subproceso en segundo plano.
        {
            return View(model);
        }

    }
}

Llano.Web/Views/User/Index.cshtml
@model List<Customer>;

@{
    ViewData["Title"] = "Usuarios";
}


<main class="u-main" role="main">
    @await Component.InvokeAsync("Sidebar")
    <div class="u-content">
        <div class="u-body">
            <!--  Tabla para mostrar todos los usuarios registrados -->
            <div class="card">
                <div class="card mb-4">
                    <header class="card-header">
                        <h2 class="h3 card-header-title">Listado de usuarios registrados</h2>
                    </header>@{
                        ViewData["Title"] = "Inicio";
                    }

                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-hover">
                                <thead>
                                    <tr>
                                        <th scope="col">#</th>
                                        <th scope="col">Nombres</th>
                                        <th scope="col">Apellidos</th>
                                        <th scope="col">telefono</th>
                                        <th scope="col">correo</th>
                                        <th class="text-center" scope="col">
                                            Accion
                                        </th>

                                    </tr>
                                </thead>

                                <tbody>
                                    @{
                                        var index = 1;
                                        foreach (var user in Model)
                                        {

                                            <tr>
                                                <td>@index</td>
                                                <td>@user.FirstName </td>
                                                <td>@user.LastName </td>
                                                <td>@user.PhoneNumber </td>
                                                <td>@user.Email </td>
                                                <td class="text-center">
                                                    <a class="d-flex text-center  align-items-center link-muted py-2 px-3" asp-controller="User" asp-action="Read" asp-route-UserId="@user.Id">
                                                        <i class="fa fa-external-link-alt mr-2"></i>
                                                    </a>
                                                </td>
                                            </tr>

                                            index = index + 1;
                                        }
                                    }

                                </tbody>
                            </table>
                        </div>
                    </div>

                </div>


            </div>

        </div>
    </div>
</main>

Llano.Web/Views/User/Read.cshtml
@model CustomerMessageViewModels
@{
    ViewData["Title"] = "Usuario";
}

<main class="u-main" role="main">
    @await Component.InvokeAsync("Sidebar")
    <div class="u-content">
        <div class="u-body">

            <div class="mb-4">
                <nav aria-label="breadcrumb">
                    <h1 style="font-family:Livvic-Medium" class="h3">@ViewData["Title"]</h1>
                </nav>
            </div>

            <form id="formUser" class="validateDontSubmit">
                <!-- Form Controls -->
                <div class="row">

                    <!-- Informacion del Usuario -->
                    <div class="col-12 mb-4">
                        <div class="card">
                            <header class="card-header">
                                <h2 class="h3 card-header-title">Información Usuario</h2>
                            </header>

                            <div class="card-body row">

                                <input type="hidden" asp-for="@Model.UserApplication.FirstName" class="form-control" required />
                                <input type="hidden" asp-for="@Model.UserApplication.LastName" class="form-control" required />
                                <input type="hidden" asp-for="@Model.UserApplication.CreatedOn" class="form-control" required />

                                <div class="form-group col-12 col-md-6 mb-4">
                                    <label for="defaultInput">Nombres y Apellidos</label>
                                    @{
                                        var nombreCompleto = Model.UserApplication.FirstName + " " + Model.UserApplication.LastName;
                                    }

                                    <span class="form-icon-wrapper">
                                        <span class="form-icon form-icon--left">
                                            <i class="fa fa-user-circle form-icon__item"></i>
                                        </span>
                                        <input value="@nombreCompleto" class="form-control form-icon-input-left" required disabled>
                                    </span>

                                </div>

                                <div class="form-group col-12 col-md-6 mb-4">
                                    <label for="defaultInput">Telefono</label>
                                    <span class="form-icon-wrapper">
                                        <span class="form-icon form-icon--left">
                                            <i class="fa fa-phone form-icon__item"></i>
                                        </span>
                                        <input value="@Model.UserApplication.PhoneNumber" class="form-control form-icon-input-left" required disabled>
                                    </span>

                                </div>

                                <div class="form-group col-12 col-md-6  mb-4">
                                    <label for="defaultInput">Correo Electronico</label>
                                    <span class="form-icon-wrapper">
                                        <span class="form-icon form-icon--left">
                                            <i class="fa fa-envelope-square form-icon__item"></i>
                                        </span>
                                        <input asp-for="@Model.UserApplication.Email" class="form-control form-icon-input-left" required disabled>

                                    </span>

                                </div>

                                <div class="form-group col-12 col-md-6  mb-4">
                                    <label for="inputLeftIcon">Fecha de Registro</label>
                                    <input value="@Model.UserApplication.CreatedOn.ToShortDateString();" class="form-control" required disabled>
                                </div>


                            </div>
                            <div class="col-12 mb-4 ">
                                <span style="float: right">
                                    <button id="eliminarUsuario" class="btn btn-danger">Eliminar</button>
                                </span>

                            </div>

                        </div>


                    </div>

                </div>





            </form>


            <!--  Tabla para mostrar los contenidos en estado solicitado -->
            <div class="card">
                <div class="card mb-4">
                    <header class="card-header">
                        <h2 class="h3 card-header-title">Lista de Recursos</h2>
                    </header>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-hover">
                                <thead>
                                    <tr>
                                        <th scope="col">#</th>
                                        <th scope="col">Nombre</th>
                                        <th scope="col">Estado</th>
                                        <th scope="col">Categoria</th>
                                        <th scope="col" width="180">Fecha solicitud</th>
                                        <th class="text-center" scope="col">
                                            Accion
                                        </th>

                                    </tr>
                                </thead>


                                <tbody>
                                    @{

                                        var index = 1;

                                        var resourcesR = Model.Resources;

                                        foreach (var resource1 in resourcesR)
                                        {

                                            <tr>
                                                <td> @index</td>
                                                <td> @resource1.Name</td>
                                                <td>

                                                    @switch (resource1.StatusResourceId)
                                                    {

                                                        case 1:
                                                            <a class="badge badge-soft-warning" href="#">Solicitado</a>
                                                            break;
                                                        case 2:
                                                            <a class="badge badge-soft-danger" href="#">Descartado</a>
                                                            break;
                                                        case 3:
                                                            <a class="badge badge-soft-success" href="#">Aprobado</a>
                                                            break;
                                                        default:
                                                            break;
                                                    }
                                                </td>

                                                <td>

                                                    @switch (resource1.TypeResource.Name)
                                                    {

                                                        case "Palabras":
                                                            <a class="badge badge-soft-success" href="#">@resource1.TypeResource.Name</a>
                                                            break;
                                                        case "Refranes":
                                                            <a class="badge badge-soft-info" href="#">@resource1.TypeResource.Name</a>
                                                            break;
                                                        case "Coplas":
                                                            <a class="badge badge-soft-warning" href="#">@resource1.TypeResource.Name</a>
                                                            break;
                                                        case "Leyendas":
                                                            <a class="badge badge-soft-danger" href="#">@resource1.TypeResource.Name</a>
                                                            break;
                                                        default:
                                                            break;
                                                    }
                                                </td>
                                                <td>@resource1.CreatedOn.ToShortDateString() </td>
                                                <td class="text-center">
                                                    <a class="d-flex text-center  align-items-center link-muted py-2 px-3" asp-controller="Resource" asp-action="Read" asp-route-idResource="@resource1.Id">
                                                        <i class="fa fa-external-link-alt mr-2"></i>
                                                    </a>
                                                </td>
                                            </tr>

                                            index = index + 1;


                                        }

                                    }
                                </tbody>
                            </table>
                        </div>
                    </div>

                </div>


            </div>

        </div>
    </div>
</main>

<!-- Modals Discarded -->
<div class="modal fade " id="modalEliminarUsuario" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content d-block">
            <div class="modal-header" style="display: block">
                <h4 style="font-family:Livvic-Medium" class="modal-title" id="exampleModalLongTitle">Eliminar Usuario</h4>
                <p>
                    Recuerde que si elimina el usuario tambien se eliminara el contenido aportado por el mismo.
                </p>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">

                @{
                    var nombreCompleto2 = Model.UserApplication.FirstName + " " + Model.UserApplication.LastName;
                }

                <form id="formDiscardedUser" asp-controller="User" asp-action="Delete" method="post">

                    <input type="hidden" asp-for="@Model.UserApplication.Id" class="form-control" required />

                    <label for="defaultInput"> Cuentale a @nombreCompleto2 por que eliminas su cuenta</label>

                    <div class="form-group col-12 mb-4">
                        <textarea asp-for="@Model.Message" class="form-control text-justify" rows="5" required></textarea>
                    </div>

                    <button type="submit" class="btn btn-danger d-none">Oculto</button>
                </form>

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                <button type="submit" form="formDiscardedUser" class="btn btn-danger">Confirmar</button>
            </div>
        </div>
    </div>
</div>